github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/circle-downloader",
"https://serp.co/products/circle-downloader/reviews/",
"https://chromewebstore.google.com/detail/circle-downloader/afjjgeafaiahjlcgnflgeojbjobglblg",
"https://whop.com/serp-downloaders/circle-downloader/"
]
